pq = gets.split().map(&:to_s)
array=[3,1,4,1,5,9]
fon=-1
back=-1
pq.each do |x|
    if(x=='A')
        if(fon==-1)
            fon=0
        else
            back=0
        end
    end
    if(x=='B')
        if(fon==-1)
            fon=1
        else
            back=1
        end    
    end
    if(x=='C')
        if(fon==-1)
            fon=2
        else
            back=2
        end
    end
    if(x=='D')
        if(fon==-1)
            fon=3
        else
            back=3
        end
    end
    if(x=='E')
        if(fon==-1)
            fon=4
        else
            back=4
        end
    end
    if(x=='F')
        if(fon==-1)
            fon=5
        else
            back=5
        end
    end
    if(x=='G')
        if(fon==-1)
            fon=6
        else
            back=6
        end
    end
end
sums=0
if(fon<back)
    fon.upto(back-1) do |k|
        sums+=array[k]
    end
else
    back.upto(fon-1) do |k|
        sums+=array[k]
    end
end
puts sums